version: '3'
services: 
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      # Means that we should not mount the node_modules directory from the host
      # This is important to avoid conflicts between host and container node_modules
      - /app/node_modules
      # map outside folder to inside the container
      - .:/app
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      # map outside folder to inside the container
      - .:/app
    command: ["npm", "run", "test"]
  